### ISSUE TITLE
failed to start. Here are the error logs:

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-service-logger-stats#1]
```
TypeError: app.hooks is not a function
  at instrumentServices (**\server\node_modules\feathers-service-logger-stats\lib\index.js:93:7)
  at EventEmitter.<anonymous> (**\server\node_modules\feathers-service-logger-stats\lib\index.js:78:5)
  at EventEmitter.configure (**\server\node_modules\feathers\lib\application.js:138:8)
  at Object.<anonymous> **\server\src\app.js:58:4)
```
After using logger-stats as the readme said, I got this eror when starting the server.

**Comment by beeplin** [comment]
And here is parts of my app.js. Anythin is wrong?

```js
...
const loggerStats = require('feathers-service-logger-stats').loggerStats;
const getPending = require('feathers-service-logger-stats').getPending;
const getStats = require('feathers-service-logger-stats').getStats;
...
app.use(favicon(path.join(app.get('path'), '../favicon.ico')))
  .use('/', serveStatic(app.get('path')))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({
    extended: true
  }))
  .configure(hooks())
  .configure(rest())
  .configure(socketio())
  .configure(services)
  .configure(loggerStats())
  .configure(middleware);
```

The app.js is all from the cli tool. I just inserted the loggerStats line after the services line.

Any one can reproduce this?

**Comment by eddyystop** [comment]
You need the latest feathers-hooks. It needs the latest feathers-commons. You can `rm -rf node_modules && npm install`.

**Comment by beeplin** [comment]
done. Now all okay. the dependence should be declared in package.json, I think.

**Comment by eddyystop** [comment]
I believe npm doesn't do co-dependencies anymore. It might just display a message on the console which is easy to miss.

The code now throws with a warning if `app.hooks !=== 'function'`.
